version: 2.1
jobs:
  build:
    docker:
      - image: python:3.7.3-alpine3.9
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
            tox
      - store_artifacts:
          path: htmlcov
      - codecov/upload:
          file: htmlcov/index.html
